steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/services/regnet-es:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/services/regnet-es:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'regnet-es', '--platform=managed', '--image=gcr.io/services/regnet-es:$SHORT_SHA', '--region=europe-west4']
